export const EXTENSION_ID = "diffchestrator";

export const VIEW_ACTIVE_REPOS = "diffchestrator.activeRepos";
export const VIEW_REPOS = "diffchestrator.repos";
export const VIEW_CHANGED_FILES = "diffchestrator.changedFiles";

export const CMD = {
  scan: "diffchestrator.scan",
  rescan: "diffchestrator.rescan",
  toggleChangedOnly: "diffchestrator.toggleChangedOnly",
  toggleFavorite: "diffchestrator.toggleFavorite",
  viewDiff: "diffchestrator.viewDiff",
  viewMultiRepoDiff: "diffchestrator.viewMultiRepoDiff",
  stageFile: "diffchestrator.stageFile",
  unstageFile: "diffchestrator.unstageFile",
  stageAll: "diffchestrator.stageAll",
  unstageAll: "diffchestrator.unstageAll",
  commit: "diffchestrator.commit",
  push: "diffchestrator.push",
  pull: "diffchestrator.pull",
  aiCommit: "diffchestrator.aiCommit",
  bulkCommit: "diffchestrator.bulkCommit",
  bulkPush: "diffchestrator.bulkPush",
  openClaudeCode: "diffchestrator.openClaudeCode",
  searchFiles: "diffchestrator.searchFiles",
  browseFiles: "diffchestrator.browseFiles",
  openTerminal: "diffchestrator.openTerminal",
  selectRepo: "diffchestrator.selectRepo",
  clearSelection: "diffchestrator.clearSelection",
  switchRepo: "diffchestrator.switchRepo",
  yolo: "diffchestrator.yolo",
  commitHistory: "diffchestrator.commitHistory",
  discardFile: "diffchestrator.discardFile",
  discardAll: "diffchestrator.discardAll",
  switchBranch: "diffchestrator.switchBranch",
  stash: "diffchestrator.stash",
  toggleBlame: "diffchestrator.toggleBlame",
  favoriteCurrent: "diffchestrator.favoriteCurrent",
  searchInRepo: "diffchestrator.searchInRepo",
  grepInRepo: "diffchestrator.grepInRepo",
  grepActiveRepos: "diffchestrator.grepActiveRepos",
  grepAllRepos: "diffchestrator.grepAllRepos",
  stageCurrentFile: "diffchestrator.stageCurrentFile",
  unstageCurrentFile: "diffchestrator.unstageCurrentFile",
  cycleActiveRepo: "diffchestrator.cycleActiveRepo",
  closeActiveRepo: "diffchestrator.closeActiveRepo",
  closePickedRepo: "diffchestrator.closePickedRepo",
  closeAllActiveRepos: "diffchestrator.closeAllActiveRepos",
  nextChangedFile: "diffchestrator.nextChangedFile",
  prevChangedFile: "diffchestrator.prevChangedFile",
  switchRoot: "diffchestrator.switchRoot",
  addScanRoot: "diffchestrator.addScanRoot",
  removeScanRoot: "diffchestrator.removeScanRoot",
  toggleShowFavorites: "diffchestrator.toggleShowFavorites",
  toggleShowFavoritesOff: "diffchestrator.toggleShowFavoritesOff",
  fetchAll: "diffchestrator.fetchAll",
  bulkPull: "diffchestrator.bulkPull",
  claudeReviewAll: "diffchestrator.claudeReviewAll",
  openRootTerminal: "diffchestrator.openRootTerminal",
  copyRepoInfo: "diffchestrator.copyRepoInfo",
  showShortcuts: "diffchestrator.showShortcuts",
  activityLog: "diffchestrator.activityLog",
  branchCleanup: "diffchestrator.branchCleanup",
  openRemoteUrl: "diffchestrator.openRemoteUrl",
  filterByTag: "diffchestrator.filterByTag",
  setRepoTag: "diffchestrator.setRepoTag",
  saveSnapshot: "diffchestrator.saveSnapshot",
  loadSnapshot: "diffchestrator.loadSnapshot",
  undoCommit: "diffchestrator.undoCommit",
  fetchRepo: "diffchestrator.fetchRepo",
  selectAllActive: "diffchestrator.selectAllActive",
  deselectAll: "diffchestrator.deselectAll",
  swapRepo: "diffchestrator.swapRepo",
} as const;

export const CONFIG = {
  scanRoots: "diffchestrator.scanRoots",
  scanMaxDepth: "diffchestrator.scanMaxDepth",
  scanExtraSkipDirs: "diffchestrator.scanExtraSkipDirs",
  scanOnStartup: "diffchestrator.scanOnStartup",
  changedOnlyDefault: "diffchestrator.changedOnlyDefault",
  autoRefreshInterval: "diffchestrator.autoRefreshInterval",
  favorites: "diffchestrator.favorites",
  claudePermissionMode: "diffchestrator.claudePermissionMode",
  showInlineBlame: "diffchestrator.showInlineBlame",
  showFavorites: "diffchestrator.showFavorites",
  fetchOnScan: "diffchestrator.fetchOnScan",
  autoPushAfterCommit: "diffchestrator.autoPushAfterCommit",
  repoTags: "diffchestrator.repoTags",
  snapshots: "diffchestrator.snapshots",
} as const;

export const CTX = {
  hasRepos: "diffchestrator.hasRepos",
  hasFavorites: "diffchestrator.hasFavorites",
  hasSelectedRepo: "diffchestrator.hasSelectedRepo",
  hasMultiSelection: "diffchestrator.hasMultiSelection",
  changedOnly: "diffchestrator.changedOnly",
  showFavorites: "diffchestrator.showFavorites",
} as const;
